# Generated by Django 5.1.6 on 2025-03-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestVision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=1),
        ),
        migrations.AddField(
            model_name='resource',
            name='gender_specific',
            field=models.CharField(choices=[('ALL', 'All'), ('F', 'Female Only'), ('M', 'Male Only')], default='ALL', max_length=3),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('FOOD', 'Food'), ('CLOTHING', 'Clothing'), ('EDUCATION', 'Education'), ('MEDICAL', 'Medical'), ('MONEY', 'Money')], max_length=20),
        ),
    ]
